#!/usr/bin/env ruby

require "rubygems/package"
require "stringio"

source = ARGV[0] or abort "Error: Missing source directory"
io = StringIO.new

Gem::Package::TarWriter.new(io) do |writer|
  Dir.chdir(source) do
    Dir.glob("**/*").each do |e|
      next if File.directory?(e)
      mode = File.lstat(e).mode
      writer.add_file(e, mode) { |fio| fio.write File.read(e, mode: "rb") }
    end
  end
end

puts File.read(__FILE__).split("__END__").last.strip
puts
puts "__END__"
puts [io.string].pack("m")

__END__

require "tmpdir"
require "rubygems/package"
require "stringio"

Dir.mktmpdir("rbz") do |dir|
  Dir.chdir(dir) do
    tar = StringIO.new(DATA.read.unpack1("m"))
    Gem::Package::TarReader.new(tar) do |reader|
      reader.each do |entry|
        next if entry.full_name.start_with?("._")
        next if entry.full_name.start_with?("PaxHeader")

        FileUtils.mkdir_p(File.dirname(entry.full_name))
        File.write(entry.full_name, entry.read, mode: "wb")
        File.chmod(entry.header.mode, entry.full_name)
      end
    end

    exec "ruby", "main.rb"
  end
end
